/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diab
 */
import java.awt.CardLayout;
import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.*;
public class Checkout extends javax.swing.JPanel {

    /**
     * Creates new form Checkout
     */
    public Checkout(JPanel mainPanel) {
        this.setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        this.mainPanel = mainPanel;
        initComponents();

    }

    public void populateTextbox()
    {

        System.out.println(OrderXML.items.pizzas.size());

        for (int i = 0; i < OrderXML.items.pizzas.size(); ++i) {
            jTextArea1.append("Pizza " + i + ": $" + PricingCalculator.getPizzaPrice(OrderXML.items.pizzas.get(i)) + "\n");
        }

        for (int i = 0; i < OrderXML.items.drinks.size(); ++i) {
            jTextArea1.append("Drink " + i + ": $" + PricingCalculator.getDrinkPrice(OrderXML.items.drinks.get(i)) + "\n");
        }
    }
    JPanel mainPanel;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkoutJB = new javax.swing.JButton();
        cancelJB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        checkoutJB.setText("Checkout");
        checkoutJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutJBActionPerformed(evt);
            }
        });

        cancelJB.setText("Cancel");
        cancelJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJBActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelJB)
                        .addGap(164, 164, 164)
                        .addComponent(checkoutJB)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkoutJB)
                    .addComponent(cancelJB))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void cancelJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJBActionPerformed
        ((CardLayout)mainPanel.getLayout()).show(mainPanel, "TopLevelMenu");
    }//GEN-LAST:event_cancelJBActionPerformed

    private void checkoutJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutJBActionPerformed
        ((CardLayout)mainPanel.getLayout()).show(mainPanel, "TopLevelMenu");
    }//GEN-LAST:event_checkoutJBActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelJB;
    private javax.swing.JButton checkoutJB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
